name = "pashusewa"
main = "src/index.js"
compatibility_date = "2023-09-01"

# Configure static assets for Pages
[site]
bucket = "./public"

# Configure D1 Database
[[d1_databases]]
binding = "DB"
database_name = "pashusewa"
database_id = "ca54923e-7f9d-4148-acee-925698bad7f1"
preview_database_id = "ca54923e-7f9d-4148-acee-925698bad7f1"

# Configure assets binding
[build]
command = ""
[build.upload]
format = "service-worker"

# Configure a route to match the site deployment
routes = [
  { pattern = "pashusewa.pashusewa-india.workers.dev", custom_domain = true }
]
