name = "pashusewa"
main = "src/index.js"
compatibility_date = "2023-09-01"

# Configure D1 Database
[[d1_databases]]
binding = "DB"
database_name = "pashusewa"
database_id = "ca54923e-7f9d-4148-acee-925698bad7f1"
preview_database_id = "ca54923e-7f9d-4148-acee-925698bad7f1"
