name = "pashusewa-backend"
main = "src/index.js"
compatibility_date = "2024-01-01"

# Configure D1 Database
[[d1_databases]]
binding = "DB"
database_name = "pashusewa-db"
database_id = "ca54923e-7f9d-4148-acee-925698bad7f1"
